language: generic
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
script:
  - jdk_switcher use oraclejdk8
  - bash travis/build.sh
env:
  global:
    secure: "ZKXsr1qRmz97Lf2mlsOjqJnCSEgJOoQRulkZKSJIl7nRPOY29LczYwvUxU1Y37uKQKp0wjDxPFr/dVcZK+sCcBtNcJb4sq8bN9r8f9H3VFbSFYnjSSIywo8XBka41++aK511kLNCRn3Fd/6ly10IMckdDy694PkZ6oK1zNDbycbKwMzDEoaBAy/2tQWK92tuvE9bdO9vUYDq6/RN/TssCmqrhZ2U5igwJIrCNKrsQh1WfDvrxjR6xpyXwmxHJqbFj1lZryhj1iUDJFFgQ62W/vAHnF8IeFq0+5XQIG5YFAAt2Wx3MNvtaQV1jdEhiU9hYLXB7+UtEVw+6B/YbjvblKl3XfOOuxrj2QZwDA0uwPycz7ARq0Ikz27GASww1BqIvpNF98fNmZlskAO7c43c3ob3y8RNTh7+wU3ErXRIvTfyoIKsTeS7vI7dGwMJjXRP3fJoXgb0VcTbz1Cix9dHl9nTeenPVFp68O/Qi7jFLO4FuVMgi1JhQ87xj0u5c85fmAULRxgcny9auBelQoOmOSTzdw13p5MDKZhy0lZnDisDHaidpdsQ0ndPI2YOeSBaplDwIoJzVeMp401zp6AK8cYnBIF9vZ70bd1T6fwVYNasE+Wm5PAk8OY0YsHcsl5XisWkoH2H0r+gEAjVzk3CmBPSbWfwiCE+zxWYS3R/yu8="
